useDotenv: true

service: ${env:AWS_SERVICE_NAME}
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  versionFunctions: false
  region: ${env:AWS_REGION}
  apiName: ${env:AWS_SERVICE_NAME}
  memorySize: 6144
  logRetentionInDays: 30
  apiGateway:
    minimumCompressionSize: 1024
  vpc:
    securityGroupIds:
      - ${file(./config/${self:provider.stage}.json):VPC_SECURITY_GROUP_ID_1}
      - ${file(./config/${self:provider.stage}.json):VPC_SECURITY_GROUP_ID_2}
    subnetIds:
      - ${file(./config/${self:provider.stage}.json):VPC_SUBNET_ID_1}
  role: ${file(./config/${self:provider.stage}.json):LAMBDA_ROLE}
  deploymentBucket:
    blockPublicAccess: true
    name: ${env:AWS_DEPLOYMENT_BUCKET}
resources:
  Description: ${env:AWS_SERVICE_NAME}
package:
  include:
    - "src/**;"
    - "package.json"
  exclude:
    - coverage/**
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: "yarn"
    includeModules: true
  serverless-offline:
    lambdaPort: 7003
    noPrependStageInUrl: true
functions:
  zipper:
    handler: src/handlers/handler.handler
    events:
      - http:
          path: /zipper
          method: post
  firstFunc:
    handler: src/handlers/stepFuncts.handler
stepFunctions:
  stateMachines:
    firstFunc:
      name: ${env:AWS_SERVICE_NAME}-firstFunc
      events:
        - http:
            path: /firstFunc
            method: get
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource:
              Fn::GetAtt: [firstFunc, Arn]
            End: true
plugins:
  - serverless-webpack
  - serverless-jest-plugin
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
  - serverless-step-functions
